-- Vyom Regency — consolidated schema
--
-- Single source of truth for the database structure. This file reflects the
-- ACTUAL live schema as of 2026-07-11 (verified by introspecting the running
-- Supabase project), not just the order migrations happened to be written in.
--
-- To rebuild the database from scratch, run this file top to bottom against
-- a fresh Supabase project. For an EXISTING project that already has some of
-- this applied, every statement below is idempotent (`if not exists`,
-- `drop policy if exists` + recreate, `on conflict do nothing`), so it is
-- safe to run again.
--
-- Older, superseded migration files live in supabase/archive/ for history
-- only — do not run them, this file already includes everything they did.


-- ============================================================
-- properties
-- ============================================================

create table if not exists public.properties (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  location text,
  price text,
  size text,
  status text default 'available',
  description text,
  features text[] default '{}',
  image_url text,
  created_at timestamptz not null default now(),
  display_type text default 'single',
  sort_order integer default 0,
  show_on_home boolean default false,
  brochure_url text,
  gallery_urls text[] default '{}',
  property_type text default 'project',
  meta_title text,
  meta_description text,
  focus_keyword text,
  video_url text,
  registry_type text,
  possession_status text,
  plots_left integer
);

alter table public.properties enable row level security;

drop policy if exists "Public can view properties" on public.properties;
create policy "Public can view properties" on public.properties for select using (true);

drop policy if exists "Authenticated can insert properties" on public.properties;
create policy "Authenticated can insert properties" on public.properties for insert with check (auth.role() = 'authenticated');

drop policy if exists "Authenticated can update properties" on public.properties;
create policy "Authenticated can update properties" on public.properties for update using (auth.role() = 'authenticated');

drop policy if exists "Authenticated can delete properties" on public.properties;
create policy "Authenticated can delete properties" on public.properties for delete using (auth.role() = 'authenticated');

-- backfill: rows that were created before property_type existed and are
-- named like an individual plot rather than a multi-plot project
update public.properties set property_type = 'individual'
where property_type is null and name ilike 'individual%';


-- ============================================================
-- blog_posts + blog_categories
-- ============================================================

create table if not exists public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  excerpt text,
  content text,
  category text,
  "categorySlug" text,
  author text,
  date text,
  "readTime" text,
  image text,
  tags text[] default '{}',
  featured boolean default false,
  created_at timestamptz not null default now(),
  meta_title text,
  meta_description text,
  focus_keyword text
);

alter table public.blog_posts enable row level security;

drop policy if exists "Public can view blog posts" on public.blog_posts;
create policy "Public can view blog posts" on public.blog_posts for select using (true);

drop policy if exists "Authenticated can insert blog posts" on public.blog_posts;
create policy "Authenticated can insert blog posts" on public.blog_posts for insert with check (auth.role() = 'authenticated');

drop policy if exists "Authenticated can update blog posts" on public.blog_posts;
create policy "Authenticated can update blog posts" on public.blog_posts for update using (auth.role() = 'authenticated');

drop policy if exists "Authenticated can delete blog posts" on public.blog_posts;
create policy "Authenticated can delete blog posts" on public.blog_posts for delete using (auth.role() = 'authenticated');

create table if not exists public.blog_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

alter table public.blog_categories enable row level security;

drop policy if exists "Public can view blog categories" on public.blog_categories;
create policy "Public can view blog categories" on public.blog_categories for select using (true);

drop policy if exists "Authenticated can manage blog categories" on public.blog_categories;
create policy "Authenticated can manage blog categories" on public.blog_categories for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

insert into public.blog_categories (name, slug) values
  ('Farmhouse Living', 'farmhouse-living'),
  ('Buying Guide', 'buying-guide'),
  ('Our Projects', 'our-projects'),
  ('Investment Guide', 'investment-guide')
on conflict (slug) do nothing;


-- ============================================================
-- gallery (photos + YouTube videos) and hero_slides
-- ============================================================

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  url text not null,
  caption text,
  created_at timestamptz not null default now(),
  media_type text default 'photo'
);

alter table public.gallery enable row level security;

drop policy if exists "Public can view gallery rows" on public.gallery;
create policy "Public can view gallery rows" on public.gallery for select using (true);

drop policy if exists "Authenticated can manage gallery" on public.gallery;
create policy "Authenticated can manage gallery" on public.gallery for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create table if not exists public.hero_slides (
  id bigint generated by default as identity primary key,
  image_url text not null,
  label text,
  sort_order integer default 0,
  created_at timestamptz not null default now()
);

alter table public.hero_slides enable row level security;

drop policy if exists "Public can view hero slides" on public.hero_slides;
create policy "Public can view hero slides" on public.hero_slides for select using (true);

drop policy if exists "Authenticated can manage hero slides" on public.hero_slides;
create policy "Authenticated can manage hero slides" on public.hero_slides for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');


-- ============================================================
-- leads, testimonials, visitor_reviews, website_feedback, settings
-- ============================================================

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  name text,
  phone text,
  email text,
  city text,
  project text,
  source text,
  status text default 'new',
  message text,
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;
drop policy if exists "Authenticated can manage leads" on public.leads;
create policy "Authenticated can manage leads" on public.leads for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "Public can insert leads" on public.leads;
create policy "Public can insert leads" on public.leads for insert with check (true);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  name text,
  location text,
  type text,
  rating integer,
  text text,
  media_type text,
  image_url text,
  video_url text,
  source text,
  status text default 'published',
  created_at timestamptz not null default now()
);

alter table public.testimonials enable row level security;
drop policy if exists "Public can view testimonials" on public.testimonials;
create policy "Public can view testimonials" on public.testimonials for select using (true);
drop policy if exists "Authenticated can manage testimonials" on public.testimonials;
create policy "Authenticated can manage testimonials" on public.testimonials for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

create table if not exists public.visitor_reviews (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  email text,
  visited_date date,
  property_name text,
  rating integer,
  experience text,
  suggestions text,
  status text default 'pending',
  created_at timestamptz not null default now()
);

alter table public.visitor_reviews enable row level security;
drop policy if exists "Authenticated can manage visitor reviews" on public.visitor_reviews;
create policy "Authenticated can manage visitor reviews" on public.visitor_reviews for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "Public can insert visitor reviews" on public.visitor_reviews;
create policy "Public can insert visitor reviews" on public.visitor_reviews for insert with check (true);

create table if not exists public.website_feedback (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  rating integer,
  experience text,
  suggestions text,
  status text default 'pending',
  created_at timestamptz not null default now()
);

alter table public.website_feedback enable row level security;
drop policy if exists "Authenticated can manage website feedback" on public.website_feedback;
create policy "Authenticated can manage website feedback" on public.website_feedback for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists "Public can insert website feedback" on public.website_feedback;
create policy "Public can insert website feedback" on public.website_feedback for insert with check (true);

create table if not exists public.site_settings (
  id integer primary key default 1,
  hero_image_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_settings enable row level security;
drop policy if exists "Public can view site settings" on public.site_settings;
create policy "Public can view site settings" on public.site_settings for select using (true);
drop policy if exists "Authenticated can update site settings" on public.site_settings;
create policy "Authenticated can update site settings" on public.site_settings for update using (auth.role() = 'authenticated');

create table if not exists public.settings (
  id integer primary key default 1,
  site_title text,
  site_description text,
  contact_phone text,
  contact_email text,
  address text
);

alter table public.settings enable row level security;
drop policy if exists "Public can view settings" on public.settings;
create policy "Public can view settings" on public.settings for select using (true);
drop policy if exists "Authenticated can manage settings" on public.settings;
create policy "Authenticated can manage settings" on public.settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');


-- ============================================================
-- SEO: page_seo (static pages) — property/blog SEO fields are
-- columns on their own tables above
-- ============================================================

create table if not exists public.page_seo (
  route text primary key,
  meta_title text,
  meta_description text,
  focus_keyword text,
  updated_at timestamptz not null default now()
);

alter table public.page_seo enable row level security;

drop policy if exists "Public can view page seo" on public.page_seo;
create policy "Public can view page seo" on public.page_seo for select using (true);

drop policy if exists "Authenticated can manage page seo" on public.page_seo;
create policy "Authenticated can manage page seo" on public.page_seo for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');


-- ============================================================
-- admin_profiles — role-based access (admin vs editor)
-- ============================================================

create table if not exists public.admin_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'editor' check (role in ('admin', 'editor')),
  created_at timestamptz not null default now()
);

alter table public.admin_profiles enable row level security;

drop policy if exists "Admins can read own profile" on public.admin_profiles;
create policy "Admins can read own profile" on public.admin_profiles for select using (auth.uid() = id);

create or replace function public.handle_new_admin_user()
returns trigger as $$
begin
  insert into public.admin_profiles (id, email, role)
  values (new.id, new.email, 'editor')
  on conflict (id) do nothing;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists on_admin_user_created on auth.users;
create trigger on_admin_user_created
  after insert on auth.users
  for each row execute function public.handle_new_admin_user();

-- Backfill profile rows for any admin users that already exist.
insert into public.admin_profiles (id, email, role)
select id, email, 'editor' from auth.users
on conflict (id) do nothing;

-- To promote an account to admin (full access to every tab/section):
--   update public.admin_profiles set role = 'admin' where email = 'you@example.com';


-- ============================================================
-- Storage buckets (all public-read; writes require an authenticated
-- session, enforced by the same "authenticated" storage policies)
-- ============================================================

insert into storage.buckets (id, name, public)
values
  ('properties', 'properties', true),
  ('blog', 'blog', true),
  ('gallery', 'gallery', true),
  ('testimonials', 'testimonials', true),
  ('hero-banners', 'hero-banners', true),
  ('brochures', 'brochures', true)
on conflict (id) do nothing;

drop policy if exists "Public can read storage objects" on storage.objects;
create policy "Public can read storage objects" on storage.objects
  for select using (bucket_id in ('properties', 'blog', 'gallery', 'testimonials', 'hero-banners', 'brochures'));

drop policy if exists "Authenticated can manage storage objects" on storage.objects;
create policy "Authenticated can manage storage objects" on storage.objects
  for all using (auth.role() = 'authenticated' and bucket_id in ('properties', 'blog', 'gallery', 'testimonials', 'hero-banners', 'brochures'))
  with check (auth.role() = 'authenticated' and bucket_id in ('properties', 'blog', 'gallery', 'testimonials', 'hero-banners', 'brochures'));
