-- Run this in the Supabase SQL Editor.

-- Hero slider: admin-managed slides instead of hardcoded images.
create table if not exists public.hero_slides (
  id bigint generated by default as identity primary key,
  image_url text not null,
  label text,
  sort_order integer default 0,
  created_at timestamptz default now()
);

alter table public.hero_slides enable row level security;

create policy "Public can view hero slides"
on public.hero_slides for select
using (true);

create policy "Authenticated can manage hero slides"
on public.hero_slides for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

-- Property gallery: multiple images per property, shown on the detail page.
alter table public.properties add column if not exists gallery_urls text[] default '{}';
