-- Dynamic blog categories (admin can add new ones instead of a hardcoded list)

create table if not exists public.blog_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

alter table public.blog_categories enable row level security;

create policy "Public can view blog categories" on public.blog_categories
  for select using (true);

create policy "Authenticated can manage blog categories" on public.blog_categories
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

insert into public.blog_categories (name, slug) values
  ('Farmhouse Living', 'farmhouse-living'),
  ('Buying Guide', 'buying-guide'),
  ('Our Projects', 'our-projects'),
  ('Investment Guide', 'investment-guide')
on conflict (slug) do nothing;
