-- Run this in the NEW project's SQL Editor if CSV import fails with:
-- "cannot insert a non-DEFAULT value into column 'id' ... GENERATED ALWAYS"
-- This switches id columns to GENERATED BY DEFAULT, which still auto-generates
-- ids for new rows but allows CSV imports to preserve the original row ids.

alter table public.gallery alter column id set generated by default;
alter table public.blog_posts alter column id set generated by default;
alter table public.testimonials alter column id set generated by default;
alter table public.visitor_reviews alter column id set generated by default;
alter table public.website_feedback alter column id set generated by default;
