-- Run this entire file in the NEW Supabase project's SQL Editor, in one go.
-- Recreates the exact schema from the old project (zlatowimbkujocjcnfeu) plus RLS policies.

-- =========================================================
-- TABLES
-- =========================================================

create table public.properties (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null,
  location text,
  price text,
  size text,
  status text default 'available',
  description text,
  features text[],
  image_url text,
  created_at timestamptz default now(),
  display_type text default 'single',
  sort_order integer default 0,
  show_on_home boolean default false
);

create table public.testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  type text,
  rating integer,
  text text not null,
  media_type text default 'text',
  image_url text,
  video_url text,
  source text default 'admin',
  status text default 'approved',
  created_at timestamptz default now()
);

create table public.visitor_reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  email text,
  visited_date date,
  property_name text,
  rating integer,
  experience text,
  suggestions text,
  status text default 'pending',
  created_at timestamptz default now()
);

create table public.website_feedback (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  rating integer,
  experience text,
  suggestions text,
  status text default 'pending',
  created_at timestamptz default now()
);

create table public.blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null,
  excerpt text,
  content text,
  category text,
  "categorySlug" text,
  author text,
  date text,
  "readTime" text,
  image text,
  tags text[] default '{}',
  featured boolean default false,
  created_at timestamptz default now()
);

create table public.gallery (
  id bigint generated by default as identity primary key,
  url text not null,
  caption text,
  created_at timestamptz default now()
);

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  email text,
  city text,
  project text,
  source text default 'website',
  status text default 'new',
  message text,
  created_at timestamptz default now()
);

create table public.settings (
  id integer primary key default 1,
  site_title text,
  site_description text,
  contact_phone text,
  contact_email text,
  address text
);

create table public.site_settings (
  id integer primary key default 1,
  hero_image_key text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Seed the singleton rows so admin pages relying on a single row (id=1) work immediately
insert into public.settings (id) values (1);
insert into public.site_settings (id, hero_image_key) values (1, 'hero/default-hero.jpg');

-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

alter table public.properties enable row level security;
alter table public.testimonials enable row level security;
alter table public.visitor_reviews enable row level security;
alter table public.website_feedback enable row level security;
alter table public.blog_posts enable row level security;
alter table public.gallery enable row level security;
alter table public.leads enable row level security;
alter table public.settings enable row level security;
alter table public.site_settings enable row level security;

-- Public (anonymous) can READ: properties, testimonials, blog_posts, site_settings
-- These are shown on the public marketing pages without login.
create policy "Public can view properties" on public.properties for select using (true);
create policy "Public can view testimonials" on public.testimonials for select using (true);
create policy "Public can view blog posts" on public.blog_posts for select using (true);
create policy "Public can view site settings" on public.site_settings for select using (true);

-- Logged-in admin (authenticated) can manage: properties, testimonials, blog_posts, site_settings
create policy "Authenticated can insert properties" on public.properties for insert with check (auth.role() = 'authenticated');
create policy "Authenticated can update properties" on public.properties for update using (auth.role() = 'authenticated');
create policy "Authenticated can delete properties" on public.properties for delete using (auth.role() = 'authenticated');

create policy "Authenticated can insert testimonials" on public.testimonials for insert with check (auth.role() = 'authenticated');
create policy "Authenticated can update testimonials" on public.testimonials for update using (auth.role() = 'authenticated');
create policy "Authenticated can delete testimonials" on public.testimonials for delete using (auth.role() = 'authenticated');

create policy "Authenticated can insert blog posts" on public.blog_posts for insert with check (auth.role() = 'authenticated');
create policy "Authenticated can update blog posts" on public.blog_posts for update using (auth.role() = 'authenticated');
create policy "Authenticated can delete blog posts" on public.blog_posts for delete using (auth.role() = 'authenticated');

create policy "Authenticated can update site settings" on public.site_settings for update using (auth.role() = 'authenticated');

-- Admin-only tables (no public access at all — leads/feedback are private,
-- gallery/settings are only ever read or written from the logged-in admin panel)
create policy "Authenticated can manage gallery" on public.gallery for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Authenticated can manage leads" on public.leads for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Authenticated can manage visitor reviews" on public.visitor_reviews for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Authenticated can manage website feedback" on public.website_feedback for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Authenticated can manage settings" on public.settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Note: public site visitor form submissions (leads, visitor_reviews, website_feedback) go through
-- Next.js API routes using the SUPABASE_SERVICE_ROLE_KEY (src/lib/supabaseServer.ts), which bypasses
-- RLS entirely — so anonymous visitors can still submit the lead/feedback forms even though these
-- tables have no public policy.
